name: Create and publish Docker Image
on:
  push:
    branches:
      - "dev"
  pull_request:
    branches:
      - "master"
      - "qa"

jobs:
  build:
    environment:
      name: ${{ github.ref_name }}
    name: build and push image
    runs-on: ubuntu-22.04
    steps:
      -
        name: checkout
        uses: actions/checkout@v4.1.1
        # with:
        #   repository: ${{ github.repository }}
      # -
      #   name: make image tag using Docker meta
      #   id: meta
      #   uses: docker/metadata-action@v5.0.0
      #   with:
      #     images: ${{ github.repository }}
      #     tags: |
      #       type=ref,event=branch
      #       type=semver,pattern={{major}}.{{minor}}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: build and push
        uses: docker/build-push-action@v5.0.0
        with:
          repository: ${{ github.repository }}
          context: .
          file: ./Dockerfile
          push: true  # ${{ github.event_name != 'pull_request' }}
          tags: ${{ github.repository }}:${{ github.ref_name}}
          # tags: ${{ secrets.DOCKER_HUB_USERNAME}}/${{  }}:${{ github.ref_name}}
          # tags: ${{ steps.meta.output.tags }}
          # labels: ${{ steps.meta.output.labels }}





